### ISSUE TITLE
No libopencv found on Linux Centos7

### ISSUE THREAD

**Issue by englianhu** [swarm-lab/videoplayR#2]
[videoplayR - a basic (for now) computer vision library for R](http://rpubs.com/sjmgarnier/videoplayR)

![untitled](https://cloud.githubusercontent.com/assets/7227582/10207184/6a178700-67fd-11e5-9ff4-3ae916a83b1c.png)

``` r
> devtools::session_info()
Session info -------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, linux-gnu           
 ui       RStudio (0.99.484)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2015-09-30 
```

**Comment by sjmgarnier** [comment]
@englianhu `yum install opencv` maybe (source: http://techieroop.com/install-opencv-in-centos/).

**Comment by englianhu** [comment]
``` diff
$sudo -i
$yum search opencv.hpp
- No matches found for: opencv.hpp
```

@sjmgarnier Installed the opencv from the link you provided, however `$yum search opencv` doesn't show the location of **opencv** I gonna `$cp /usr/lib64/.. /usr/lib64/..` as well as the destination location.

Tried to refer [Installing pkg-config files to proper path on CentOS with automake](http://stackoverflow.com/questions/28997618/installing-pkg-config-files-to-proper-path-on-centos-with-automake) but don't solve the installation problem.

``` diff
- package opencv was not found in the pkg-config search path.
```

![untitled](https://cloud.githubusercontent.com/assets/7227582/10210126/a3e344ac-6815-11e5-9e1a-bf00461bfcd0.png)

**Comment by sjmgarnier** [comment]
@englianhu The opencv.pc file has probably not been created yet. This might help: http://melhorum.blogspot.com/2014/04/package-opencv-was-not-found-centos-65.html.

**Comment by sjmgarnier** [comment]
@englianhu Did you manage to get pkg-config to find opencv? I will close this issue now because this is not a problem with videoplayR per se. However I would be interested if you could post here the instructions to make videoplayR run under centos, and I'll add them to the package vignette.

**Comment by englianhu** [comment]
``` diff
$ locate opencv.pc
$ 
```

Cannot find where is **opencv** located prior to `$rm xxxxxx`, is it possible to auto install opencv and relocate by `install.packages('videoplayR')` or `devtools::install_github('swarm-lab/videoplayR')`?

**Comment by sjmgarnier** [comment]
@englianhu Try `yum install opencv-devel`. It seems that the name of the OpenCV development package on centos is different from the name on other yum-based systems.

**Comment by sjmgarnier** [comment]
@englianhu And to answer your question, it should be possible one day to ship opencv directly with videoplayR, but it is going to be very complicated to implement apparently. For now, the package will rely on users installing OpenCV manually.
