### ISSUE TITLE
Installation issues on OS X related to opencv version

### ISSUE THREAD

**Issue by xjlc** [swarm-lab/videoplayR#5]
Cool project! I'd love to use it, and also see more of OpenCV wrapped and accessible from R.

However, I have installation issues on a Mac (10.11.6). Here is the critical section of the install log:

```
> devtools::install_github("swarm-lab/videoplayR")
[...]
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/jochen/Library/R/3.3/library/videoplayR/libs/videoplayR.so':
  dlopen(/Users/jochen/Library/R/3.3/library/videoplayR/libs/videoplayR.so, 6): Library not loaded: lib/libopencv_shape.3.0.dylib
  Referenced from: /Users/jochen/Library/R/3.3/library/videoplayR/libs/videoplayR.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Users/jochen/Library/R/3.3/library/videoplayR’
Error: Command failed (1)
```

This seems to make sense because opencv3 as installed via homebrew has version number 3.1, so the following can be found in /usr/local/opt/opencv3/lib/:
libopencv_shape.3.1.dylib
libopencv_shape.dylib

But not libopencv_shape.3.0.dylib

**Comment by xjlc** [comment]
Sorry, it installed fine on a cleaner machine with the same OS. Must have been some version conflict on my side

**Comment by sjmgarnier** [comment]
@xjlc Yes, probably a version conflict. This is the exact reason why I stopped developing videoplayR and started developing the [ROpenCVLite](https://github.com/swarm-lab/ROpenCVLite) and [Rvision](https://github.com/swarm-lab/Rvision) companion packages instead. The first one compiles and installs OpenCV within R. The second one is a reimplementation of videoplayR based on ROpenCVLite. It's still at an early stage of development, and there is still a lot of work to do, but the basic functions are all mostly working now.
