### ISSUE TITLE
Installation Problem 

### ISSUE THREAD

**Issue by janbaumi** [swarm-lab/videoplayR#6]
I would like to work with videoplayR but I have problem with the installation. I installed opencv with Homebrew and after that I tried to install the package with   devtools::install_github("swarm-lab/videoplayR"). The R-Console output "Could not find build tools necessary to build videoplayR". What could be the reason for that?
Sorry for my bad english. 

Thanks

**Comment by sjmgarnier** [comment]
@janbaumi I've stopped the development of videoplayR and I am in the process of replacing it with two packages called ROpenCVLite (https://github.com/swarm-lab/ROpenCVLite) and RVision (https://github.com/swarm-lab/Rvision). ROpenCVLite should make it easy to install OpenCV directly within R in a standardized fashion while RVision will take advantage of ROpenCVLite to offer a basic computer library for R. Both packages are still in an early development stage, but they should be both functional on Mac, Linux and Windows.

**Comment by dtracy198** [comment]
Hello, 
If you need to try this to install it on a Mac in the mean time, follow the following steps.

First you need install homebrew by running the following code in the terminal: 
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Secondly, install ovenCV 3.0.0 with the following code:
     brew tap homebrew/science
     brew install https://raw.githubusercontent.com/Homebrew/homebrew-science/d154fff3192ab13bb69b0b7cb5b297a947a565e2/opencv3.rb
     brew link opencv3 --force
     brew pin opencv3

Afterwards you should be able to open R and run the following code:
Install VideoPlayR
 if (!require(devtools)) {
   install.packages("devtools")
 }
devtools::install_github("swarm-lab/videoplayR")

Thanks Simon this application has worked great for our needs and Justin has been making headway with your newer applications.

**Comment by sjmgarnier** [comment]
Thanks for the workaround @dtracy198. I will close this issue. 

ROpenCVLite/RVision are still in an early stage of development, but I will try improving on them as soon as I can find the time. It would be very helpful to know what functionalities you would like to see in RVision, so don't hesitate to open issues on the RVision repo to request new features.
