### ISSUE TITLE
ERROR: compilation failed for package 'Rcpp Armadillo'

### ISSUE THREAD

**Issue by rendaths** [swarm-lab/videoplayR#7]
Hi everyone, I'm trying to install videoplayR in  linux ( Ubuntu 14.04) and I got this error
/usr/bin/ld: cannot found - llapack
/usr/bin/ld: cannot found - lblas
collector2: error: ld returned 1 exit status
ERROR: compilation failed for package 'RcppArmadillo'
* removing '......../RcppArmadillo'
error: Command failed (1)

How can I fix this error?

**Comment by sjmgarnier** [comment]
This is a problem with installing the RcppArmadillo package. You should contact the package developer regarding this error: https://github.com/RcppCore/RcppArmadillo

**Comment by sjmgarnier** [comment]
@rendaths Also, videoplayR is not developed anymore. You should consider using Rvision instead (https://github.com/swarm-lab/Rvision).
