### ISSUE TITLE
videoplayR and R shiny

### ISSUE THREAD

**Issue by KolmogorovJr** [swarm-lab/videoplayR#8]
Hi,

Anyone tried to use the videoplayR package in R shiny application?
It works fine on my local machine but when I want to share my application
online through the public server (https://www.shinyapps.io/), I have errors in
the package installation ("package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable").
Any suggestion to install opencv on the https://www.shinyapps.io/ server ?
Thank you

Thibaut

**Comment by sjmgarnier** [comment]
@KolmogorovJr I've stopped the development of videoplayR and I am in the process of replacing it with two packages called ROpenCVLite (https://github.com/swarm-lab/ROpenCVLite) and RVision (https://github.com/swarm-lab/Rvision). ROpenCVLite should make it easy to install OpenCV directly within R in a standardized fashion while RVision will take advantage of ROpenCVLite to offer a basic computer library for R. Both packages are still in an early development stage, but they should be both functional on Mac, Linux and Windows. 

These libraries can be used without problem with Shiny on a private Shiny or shinyProxy server. Regarding whether these new libraries can be installed on shinyapps.io, you will have to contact their admins directly to ask them whether they will authorize it (ROpenCVLite will download and compile opencv, which might require special permissions on shinyapps.io servers).
