### ISSUE TITLE
Error while installing videoplayR

### ISSUE THREAD

**Issue by gnanaprakashtcs** [swarm-lab/videoplayR#9]
Error: Failed to install 'videoplayR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/GNANAP~1/AppData/Local/Temp/RtmpK2EwYI/file362066a61afd/videoplayR_0.3.1.tar.gz’ had non-zero exit status

**Comment by sjmgarnier** [comment]
@gnanaprakashtcs videoplayR is not developed anymore. Please use Rvision instead: https://github.com/swarm-lab/Rvision
